### PR TITLE
Week 1

### PR DESCRIPTION
**Pull request by Mirvdijk**

### CODE REVIEW

**Comment by Mirvdijk** [comment]
I believe there is a merge confllict due to the earlier README file that I had. In a new branch I adjusted the README file that resulted in this conflict. However, I do not know how to resolve this.

**Comment by vandenman** [comment]
Please do not merge this pull request yourself but wait until the next class!

**Comment by kmrdknrd** [comment]
Package structure looks good! I would add an `example.py` file in `Shazam/Shazam`, so that the user can check if installation worked for them.

A potential extension of the project could be song recommendations. Once an audio clip is identified as "most likely to be 'song X' ", you could present the user with the next most likely candidates as song recommendations:)

**Comment by piakoch** [comment]
This sounds super cool and ambituous! 
I found this repository on github: 
https://github.com/MohReza86/Music-Identifier

Maybe you can take some inspiration from it since they also use fourier transformation but a short time fourier transformation (STFT) so you can define how short you want the music snippets to be in order for your program to identify them. I also wonder which song database you will use that your package can choose from. 

The structure looks good, nothing to add.

**Pull request merged**
